import { esc, money, reportCss, actionBar, actionScript, taxSection } from './report-ui.mjs';

export function buildCombinedReportHTML({ part1Metadata, part1Result, part1Audit, part1Supplemental, part1Extras, part2Metadata, part2Audit, part2Extras, mode='summary' }) {
  const full = mode === 'full';
  const payrollTotal = Number(((part1Audit?.payrollRetro||0)+(part2Audit?.payrollRetro||0)).toFixed(2));
  const independentTotal = part2Audit?.reconstructedRetro == null ? null : Number(((part1Audit?.reconstructedRetro||0)+part2Audit.reconstructedRetro).toFixed(2));
  const totalDifference = independentTotal == null ? null : Number((payrollTotal-independentTotal).toFixed(2));
  const mainGood = ['reconciled','reconciled-minor-unresolved'].includes(part1Result?.calculation?.status);
  const laterGood = part2Audit?.status === 'reconciled';
  const overall = mainGood && laterGood && totalDifference != null && Math.abs(totalDifference) <= 1.00;
  const night = part2Audit?.directComponents?.find((x)=>x.payCode==='Night Shift Differential')?.actual || 0;
  const resource = part2Audit?.directComponents?.find((x)=>x.payCode==='Charge Pay')?.actual || 0;
  const benefitMain = Number(part1Extras?.postTaxHistoricalTotal || 0);
  const benefitLater = Number(part2Extras?.postTaxHistoricalTotal || 0);
  const benefitTotal = Number((benefitMain + benefitLater).toFixed(2));
  const stories = [
    ['The 9/3 payment corrected the main wage rates.','This is the original retro payment tied to the negotiated wage-scale increases.'],
    ['The 9/24 payment corrected Night and Resource / Flow.','Night moved from $5.00 to $5.50 and Resource / Flow from $3.50 to $3.75 on the historical adjustment rows.'],
    ['The 9/24 payment recalculated overtime again.','That is expected because higher Night / Resource pay can raise the weekly OT rate.'],
  ];
  if (benefitTotal) stories.push(['Workday also made dated benefit-deduction adjustments.',`Across the two statements, the dated historical adjustments total ${money(benefitTotal)} (${money(benefitMain)} on 9/3 and ${money(benefitLater)} on 9/24). They are deductions, not retro wages, and the checker does not verify the insurance-plan premium formula.`]);
  const detail = full ? `<section class="section"><h2>Detailed statement results</h2><div class="card"><h3>Main retro · 9/3</h3><div class="row"><span>Workday</span><b>${money(part1Audit?.payrollRetro)}</b></div><div class="row"><span>Independent reconstruction</span><b>${money(part1Audit?.reconstructedRetro)}</b></div><div class="row"><span>Difference</span><b>${money(Math.abs(part1Audit?.difference||0))}</b></div><div class="small muted" style="margin-top:7px">Check date ${esc(part1Metadata?.checkDate||'unknown')} · ${esc(part1Result?.calculation?.title||'')}</div></div><div class="card"><h3>Night & Resource retro · 9/24</h3><div class="row"><span>Workday</span><b>${money(part2Audit?.payrollRetro)}</b></div><div class="row"><span>Independent reconstruction</span><b>${part2Audit?.reconstructedRetro==null?'—':money(part2Audit.reconstructedRetro)}</b></div><div class="row"><span>Difference</span><b>${part2Audit?.difference==null?'—':money(Math.abs(part2Audit.difference))}</b></div><div class="row"><span>Independent ordinary OT reconstruction</span><b>${part2Audit?.ordinaryOtExpected==null?'—':money(part2Audit.ordinaryOtExpected)}</b></div><div class="row"><span>Independent Holiday OT reconstruction</span><b>${part2Audit?.holidayOtExpected==null?'—':money(part2Audit.holidayOtExpected)}</b></div><div class="small muted" style="margin-top:7px">Check date ${esc(part2Metadata?.checkDate||'unknown')}</div></div></section>` : '';
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#063d75"><title>Your Complete Retro Picture</title><style>${reportCss()}</style></head><body><main class="report">${actionBar()}<article class="sheet"><header><h1>Your Complete Retro Picture</h1><div class="kicker">Main retro ${esc(part1Metadata?.checkDate||'')} + Night & Resource retro ${esc(part2Metadata?.checkDate||'')} · ${full?'Detailed report':'Summary'}</div></header><div class="hero ${overall?'good':'partial'}"><h2>${overall?'Your two retro payments reconcile':'The combined retro needs a little more review'}</h2><p>${overall?'The 9/3 main retro and 9/24 Night & Resource retro reconcile together within conservative payroll-rounding tolerance.':'At least one payment could not be fully reconstructed under the validated rules. The details below show where uncertainty remains.'}</p></div>
  <div class="numbers"><div class="number"><span>Total Workday retro</span><b>${money(payrollTotal)}</b></div><div class="number"><span>Independent total</span><b>${independentTotal==null?'—':money(independentTotal)}</b></div><div class="number"><span>Difference</span><b>${totalDifference==null?'—':money(Math.abs(totalDifference))}</b></div></div>
  <section class="section"><h2>Retro timeline</h2><div class="timeline"><div class="timepoint"><b>4/6/2025</b><span>Retro period begins</span></div><div class="timepoint"><b>${esc(part1Metadata?.checkDate||'9/3')}</b><span>Main wage retro</span></div><div class="timepoint"><b>${esc(part2Metadata?.checkDate||'9/24')}</b><span>Night / Resource retro</span></div></div></section>
  <section class="section"><h2>Your complete retro picture</h2><div class="card"><div class="row"><span>Main retro · 9/3</span><b>${money(part1Audit?.payrollRetro)}</b></div><div class="row"><span>Night & Resource retro · 9/24</span><b>${money(part2Audit?.payrollRetro)}</b></div><div class="row"><span>&nbsp;&nbsp;Night differential correction</span><b>${money(night)}</b></div><div class="row"><span>&nbsp;&nbsp;Resource / Flow correction</span><b>${money(resource)}</b></div><div class="row"><span>&nbsp;&nbsp;Ordinary OT correction</span><b>${money(part2Audit?.ordinaryOtActual)}</b></div><div class="row"><span>&nbsp;&nbsp;Holiday OT correction</span><b>${money(part2Audit?.holidayOtActual)}</b></div></div></section>
  <section class="section"><h2>What changed</h2><div class="card plainsteps">${stories.map((x,i)=>`<div class="plainstep"><div class="dot">${i+1}</div><div><b>${esc(x[0])}</b><div class="small muted">${esc(x[1])}</div></div></div>`).join('')}</div></section>
  ${detail}${taxSection(part1Extras,'Taxes and deductions · 9/3')}${taxSection(part2Extras,'Taxes and deductions · 9/24')}
  <section class="section"><div class="callout info small"><b>Scope:</b> this report checks what can be supported by the two Workday statements. It cannot prove that every eligible hour or assignment was entered correctly before payroll ran.</div></section><footer class="reportfooter">Retro Pay Checker · Created by Andrew Raposo · Independent community tool · Not affiliated with UMass Memorial or MNA<br>Calculation model 2026.09.23</footer></article></main>${actionScript({filename:`Retro-Pay-Checker-Complete-${mode}.html`,shareText:'My complete Retro Pay Checker report',eventPrefix:`combined-report-${mode}`})}</body></html>`;
}
