export const PAY_RULES = [
  {
    id: 'flat-dollar-certification-bonus',
    title: 'Certification bonus',
    plainEnglish: 'A certification bonus is a flat $500 payment. The numbers Workday shows in the Hours and Rate columns for this item do not behave like ordinary hourly pay.',
    formula: 'certificationPayment = flat dollar amount',
    confidence: 'verified-contract-plus-payroll',
    affects: ['Certification Bonus'],
    notes: 'Do not treat the Hours field as literal paid hours for this item. Its effect on OT still needs more real examples.',
  },
  {
    id: 'retro-benefit-deduction-adjustments',
    title: 'Small dated insurance adjustments',
    plainEnglish: 'A retro statement can show many small dated insurance adjustments in addition to the normal deduction for the current check. These are historical adjustments, not the full insurance premium being charged over and over.',
    formula: null,
    confidence: 'observed-multiple-real-lines',
    affects: ['AD&D', 'Long Term Disability', 'Short Term Disability', 'Supplemental Life'],
    notes: 'RetroCalc does not yet check whether every insurance adjustment amount is correct.',
  },
  {
    id: 'weighted-regular-rate',
    title: 'Why extra pay can raise your OT rate',
    plainEnglish: 'Some extra pay, such as Baylor, Night, Weekend, Resource / Flow, Preceptor, or certain holiday pay, can raise the OT rate for that week.',
    formula: 'weeklyRegularRate = baseRate + extraPayIncludedInOT / hoursCountedForOT',
    confidence: 'highly-validated',
    affects: ['Overtime Pay', 'Holiday Overtime'],
    notes: 'The exact list of extra pay that counts can depend on the pay type and week.',
  },
  {
    id: 'ordinary-overtime-rate',
    title: 'Why your OT rate changes from week to week',
    plainEnglish: 'Your OT rate is not always just 1.5 times your base rate. Because some extra pay can raise the OT rate, two weeks with the same base rate can still have different OT rates.',
    formula: 'otRate = baseRate + 0.5 × weeklyRegularRate',
    confidence: 'verified-contract-plus-payroll',
    affects: ['Overtime Pay'],
    notes: 'RetroCalc checks OT week by week instead of using one average OT rate.',
  },
  {
    id: 'baylor-ot-treatment',
    title: 'Baylor pay and OT',
    plainEnglish: 'Baylor pay can raise the OT rate, but the extra Baylor pay hours are not counted as hours worked when that weekly rate is calculated.',
    formula: null,
    confidence: 'verified-contract-plus-payroll',
    affects: ['Baylor Time', 'Overtime Pay', 'Holiday Overtime'],
    notes: 'This is why Baylor OT retro can be a little higher than a simple 1.5-times wage difference.',
  },
  {
    id: 'sick-ot-divisor',
    title: 'Sick time and OT',
    plainEnglish: 'Sick time is not counted among the hours used to calculate the weekly OT rate.',
    formula: null,
    confidence: 'verified-contract-plus-payroll',
    affects: ['Sick Pay', 'MA Sick', 'Overtime Pay', 'Holiday Overtime'],
    notes: 'Supported by the contract and real payroll examples.',
  },
  {
    id: 'personal-ot-divisor',
    title: 'Unscheduled personal time and OT',
    plainEnglish: 'In the payroll examples checked so far, Unscheduled Personal time was not counted among the hours used to calculate the weekly OT rate.',
    formula: null,
    confidence: 'well-supported',
    affects: ['Unscheduled Personal', 'Overtime Pay'],
    notes: 'More examples are needed before treating this as universal.',
  },
  {
    id: 'major-holiday-work',
    title: 'Major holiday pay',
    plainEnglish: 'Hours worked on a major holiday are paid at 1.5 times base when those hours are not already OT. Other applicable differentials still apply.',
    formula: 'holidayRate = 1.5 × baseRate',
    confidence: 'verified-contract-plus-payroll',
    affects: ['Holiday Worked OT'],
    notes: 'Observed Workday rates match the contract rule in the examples checked.',
  },
  {
    id: 'holiday-ot-extra-half',
    title: 'Major holiday hours that are also OT',
    plainEnglish: 'When major-holiday hours are already OT, Workday can show the OT payment plus a separate extra half-time holiday payment.',
    formula: 'extraHolidayPay = 0.5 × baseRate',
    confidence: 'highly-validated',
    affects: ['Holiday Overtime', 'Holiday Worked 0.5'],
    notes: 'This pattern has repeated across the holiday examples checked.',
  },
  {
    id: 'fixed-diff-retro-repost',
    title: 'Why old differential lines may cancel to $0',
    plainEnglish: 'Workday may reverse and repost an old fixed differential at the same rate. That produces no direct retro dollars on the first check, but the line can still matter because it can affect OT.',
    formula: null,
    confidence: 'highly-validated',
    affects: ['Charge Pay', 'Evening Shift', 'Night Shift Differential', 'Weekend Differential', 'Preceptor'],
    notes: 'Night and Resource / Flow increases are being paid separately under the current implementation guidance.',
  },
  {
    id: 'retro-scope',
    title: 'What RetroCalc can check from this PDF',
    plainEnglish: 'RetroCalc checks whether the hours and pay shown by Workday were recalculated correctly. The retro PDF alone cannot prove that every hour you actually worked was recorded correctly in the first place.',
    formula: null,
    confidence: 'scope-definition',
    affects: [],
    notes: 'Checking the original time record would require another source, such as timecards, schedules, punches, or older pay stubs.',
  },
];

export function getPayRule(id) {
  return PAY_RULES.find((rule) => rule.id === id) || null;
}
